Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

convention:Metrics/CyclomaticComplexity
  Max: 11

convention:Style/MixinUsage:
  Enabled: false

convention:Style/OptionalBooleanParameter:
  Enabled: false

convention:Gemspec/RequiredRubyVersion:
  Enabled: false

convention:Metrics/AbcSize:
  Enabled: false